[package]
distribution = "2201.0.0"
org = "ballerinax"
name = "azure_eventhub"
version = "2.2.0"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["IT Operations/Data Ingestion", "Cost/Paid", "Vendor/Microsoft"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-azure.eventhub"
