[package]
org = "ballerinax"
name = "azure_eventhub"
version = "2.0.0"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["IT Operations/Data Ingestion", "Cost/Paid", "Vendor/Microsoft"]
repository = "https://github.com/ballerina-platform/module-ballerinax-azure.eventhub"
